version: "2"
services:
  mongo:
    image: mongo:3.6
  
  rabbit:
    image: rabbitmq:3

  frontend:
    image: nginx
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - app 
      - app2
      - app3

  app:  &app
    environment:
      - APP_CONFIG=chat.config.Docker
    build:
      context: ./
      dockerfile: Dockerfile 
    depends_on:
      - mongo
      - rabbit

  app2: 
    <<: *app
    ports:
      - 8001:5000

  app3:
    <<: *app
    ports:
      - 8002:5000

